name: Deploy

'on':
  push:
    branches:
      - main

concurrency:
  group: 'production'
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run check

      - name: Install Playwright browsers
        run: npx playwright install chromium firefox --with-deps

      - name: Run unit tests
        run: npm run test:unit -- --run

      - name: Run e2e tests
        run: npm run test:e2e

  deploy:
    needs: quality-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PNG2JPG_CO }}'
          projectId: png2jpg-co
          channelId: live
          expires: 30d
          target: page
          force: true
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
